src/Entity/Forfait.php
<?php

namespace App\Entity;

use App\Repository\ForfaitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ForfaitRepository::class)
 */
class Forfait
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $NomFormule;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $NumFormule;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Quantite;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $MontantQ;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $NombreH;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $MontantH;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $TVA;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="Forfaits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Author;

    /**
     * @ORM\ManyToMany(targetEntity=Collaborateur::class, mappedBy="ForfaitsCollabs")
     */
    private $CollaborateursForfaits;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Remise;

    public function __construct()
    {
        $this->CollaborateursForfaits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFormule(): ?string
    {
        return $this->NomFormule;
    }

    public function setNomFormule(?string $NomFormule): self
    {
        $this->NomFormule = $NomFormule;

        return $this;
    }

    public function getNumFormule(): ?string
    {
        return $this->NumFormule;
    }

    public function setNumFormule(?string $NumFormule): self
    {
        $this->NumFormule = $NumFormule;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->Quantite;
    }

    public function setQuantite(?int $Quantite): self
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    public function getMontantQ(): ?float
    {
        return $this->MontantQ;
    }

    public function setMontantQ(?float $MontantQ): self
    {
        $this->MontantQ = $MontantQ;

        return $this;
    }

    public function getNombreH(): ?float
    {
        return $this->NombreH;
    }

    public function setNombreH(?float $NombreH): self
    {
        $this->NombreH = $NombreH;

        return $this;
    }

    public function getMontantH(): ?float
    {
        return $this->MontantH;
    }

    public function setMontantH(?float $MontantH): self
    {
        $this->MontantH = $MontantH;

        return $this;
    }

    public function getTVA(): ?float
    {
        return $this->TVA;
    }

    public function setTVA(?float $TVA): self
    {
        $this->TVA = $TVA;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    /**
     * @return Collection<int, Collaborateur>
     */
    public function getCollaborateursForfaits(): Collection
    {
        return $this->CollaborateursForfaits;
    }

    public function addCollaborateursForfait(Collaborateur $collaborateursForfait): self
    {
        if (!$this->CollaborateursForfaits->contains($collaborateursForfait)) {
            $this->CollaborateursForfaits[] = $collaborateursForfait;
            $collaborateursForfait->addForfaitsCollab($this);
        }

        return $this;
    }

    public function removeCollaborateursForfait(Collaborateur $collaborateursForfait): self
    {
        if ($this->CollaborateursForfaits->removeElement($collaborateursForfait)) {
            $collaborateursForfait->removeForfaitsCollab($this);
        }

        return $this;
    }

    public function getRemise(): ?float
    {
        return $this->Remise;
    }

    public function setRemise(?float $Remise): self
    {
        $this->Remise = $Remise;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = ['ROLE_USER'];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Entreprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Telephone;

    /**
     * @ORM\Column(type="date")
     */
    private $DateNaissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $SIRET;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $SIREN;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $AdresseUser;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $AdresseEntreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CodePostal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pays;

    /**
     * @ORM\OneToMany(targetEntity=Collaborateur::class, mappedBy="User")
     */
    private $Collaborateurs;

    /**
     * @ORM\OneToMany(targetEntity=Forfait::class, mappedBy="User")
     */
    private $Forfaits;

    /**
     * @ORM\OneToMany(targetEntity=Facture::class, mappedBy="User")
     */
    private $Factures;

    public function __construct()
    {
        $this->Collaborateurs = new ArrayCollection();
        $this->Forfaits = new ArrayCollection();
        $this->Factures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->Entreprise;
    }

    public function setEntreprise(string $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(?string $Telephone): self
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->DateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $DateNaissance): self
    {
        $this->DateNaissance = $DateNaissance;

        return $this;
    }

    public function getSIRET(): ?string
    {
        return $this->SIRET;
    }

    public function setSIRET(?string $SIRET): self
    {
        $this->SIRET = $SIRET;

        return $this;
    }

    public function getSIREN(): ?string
    {
        return $this->SIREN;
    }

    public function setSIREN(?string $SIREN): self
    {
        $this->SIREN = $SIREN;

        return $this;
    }

    public function getAdresseUser(): ?string
    {
        return $this->AdresseUser;
    }

    public function setAdresseUser(?string $AdresseUser): self
    {
        $this->AdresseUser = $AdresseUser;

        return $this;
    }

    public function getAdresseEntreprise(): ?string
    {
        return $this->AdresseEntreprise;
    }

    public function setAdresseEntreprise(?string $AdresseEntreprise): self
    {
        $this->AdresseEntreprise = $AdresseEntreprise;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->CodePostal;
    }

    public function setCodePostal(?string $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(?string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): self
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function __toString()
    {
        return $this->Nom;
    }

    /**
     * @return Collection<int, Collaborateur>
     */
    public function getCollaborateurs(): Collection
    {
        return $this->Collaborateurs;
    }

    public function addCollaborateur(Collaborateur $collaborateur): self
    {
        if (!$this->Collaborateurs->contains($collaborateur)) {
            $this->Collaborateurs[] = $collaborateur;
            $collaborateur->setAuthor($this);
        }

        return $this;
    }

    public function removeCollaborateur(Collaborateur $collaborateur): self
    {
        if ($this->Collaborateurs->removeElement($collaborateur)) {
            // set the owning side to null (unless already changed)
            if ($collaborateur->getAuthor() === $this) {
                $collaborateur->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Forfait>
     */
    public function getForfaits(): Collection
    {
        return $this->Forfaits;
    }

    public function addForfait(Forfait $forfait): self
    {
        if (!$this->Forfaits->contains($forfait)) {
            $this->Forfaits[] = $forfait;
            $forfait->setAuthor($this);
        }

        return $this;
    }

    public function removeForfait(Forfait $forfait): self
    {
        if ($this->Forfaits->removeElement($forfait)) {
            // set the owning side to null (unless already changed)
            if ($forfait->getAuthor() === $this) {
                $forfait->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getFactures(): Collection
    {
        return $this->Factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->Factures->contains($facture)) {
            $this->Factures[] = $facture;
            $facture->setAuthor($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->Factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getAuthor() === $this) {
                $facture->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType as TypeDateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType as TypeTextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom', TypeTextType::class, [
                'label' => 'Nom', ])
            ->add('Prenom', TypeTextType::class, [
                'label' => 'Prénom', ])
            ->add('DateNaissance', TypeDateType::class, [
                'label' => 'Né(e) le',
                'attr' => ['placeholder' => 'dd/mm/yyyy'],
                'widget' => 'single_text',
                'format' => 'dd/MM/yyyy',
                'input' => 'datetime',
                'html5' => false,
                'required' => true,
                ])
            ->add('Telephone', TypeTextType::class, [
                'label' => 'Téléphone', ])
            ->add('SIRET', TypeTextType::class, [
                'label' => 'N° SIRET', ])
            ->add('Entreprise', TypeTextType::class, [
                'label' => 'Nom de l\'entreprise', ])
            ->add('SIREN', TypeTextType::class, [
                'label' => 'N° SIREN', ])
            ->add('AdresseUser', TypeTextType::class, [
                'label' => 'Adresse postale', ])
            ->add('AdresseEntreprise', TypeTextType::class, [
                'label' => 'Adresse de l\'entreprise', ])
            ->add('CodePostal', TypeTextType::class, [
                'label' => 'Code Postale', ])
            ->add('Ville', TypeTextType::class, [
                'label' => 'Ville', ])
            ->add('email', EmailType::class, [
                'label' => 'Adresse Mail', ])
            ->add('password', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
                'attr' => ['autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez renseigner un mot de passe.',
                    ]),
                    new Length([
                        'min' => 6,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        // max length allowed by Symfony for security reasons
                        'max' => 4096,
                    ]),
                ],
            ])
            // ->add('J\'accepte les termes', CheckboxType::class, [
            //     'mapped' => false,
            //     'constraints' => [
            //         new IsTrue([
            //             'message' => 'Vous devez cocher la case.',
            //         ]),
            //     ],
            // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_profil') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <div class="container">
		<div class="container" style="text-align: center; font-weight: bold; font-style: italic; margin: 9px">
			<h1>GESTIONO</h1>
		</div>

		<div class="row">
			<div class="col-sm-3">
				<div class="card">
					<div class="card-body">
						<div class="card-body">
							<h5 class="card-title">{{ user.Nom }}
								{{ user.Prenom }}</h5>
							<cite>Entreprise:</cite>
							<p class="card-text">
								{{ user.Entreprise }}</p>
						</div>
					</div>
					<ul class="list-group list-group-flush">
						<li class="list-group-item">Mail:
							{{ user.email }}</li>
						<li class="list-group-item">Adresse:
							{{ user.AdresseEntreprise }}</li>
						<li class="list-group-item">Code Postale:
							{{ user.codePostal }}</li>
						<li class="list-group-item">Ville:
							{{ user.Ville }}</li>
						<li class="list-group-item">Pays: {{ user.Pays }}</li>
					</ul>
					<div class="card-body" style="background: #edede9">
						<a href="{{path('app_user_edit',{'id':user.id})}}" class="card-link">Modifier Profil</a>
						<a href="#" class="card-link">(chercher fonctionnalité)</a>
					</div>
				</div>


			</div>
			<div class="col-sm-9">
				<div class="container" style="border: 1px solid #f8f9fa; border-radius: 20px;">
					<div class="card-body">
						{% for collaborateur in pagination %}
							<div class="container bg-light" style="border-radius: 20px; margin: 9px 0 9px 0; padding: 20px; ">
								<h5>
									<a href="{{ path('app_collaborateur_show', {'id': collaborateur.id}) }}">{{ collaborateur.nom }}
										{{ collaborateur.prenom }}</a>
								</h5>
								<p class="title" style="margin-bottom: 1px">Entreprise:
									{{ collaborateur.entreprise }}
									Mail:
									{{ collaborateur.Email }}
									Téléphone:
									{{ collaborateur.telephone }}
									Code postal:
									{{ collaborateur.codePostal }}
									Ville:
									{{ collaborateur.Ville }}
								</p>
								<div class="container">
									<p style="margin-bottom: 1px">Liste des forfaits:</p>
									{% for forfait in collaborateur.ForfaitsCollabs %}
										<div class="card bg-light mb-6" style="max-width: 50rem; margin-bottom: 8px;">
											<div class="card-header">
												nom de la formule:
												<a href="{{path('app_forfait_show',{'id':forfait.id})}}">{{ forfait.nomFormule }}</a>
											</div>
											<div class="card-body">
												<h5 class="card-title">Formule: n°
													{{ forfait.numFormule }}</h5>
												<p class="card-text">{{ forfait.description }}</p>
											</div>
										</div>

									{% else %}
										<p>Aucune formule enregistrer</p>
									{% endfor %}
								</div>
								<div class="col-2" style="margin-left: 85%; margin-top: 5px">
									<a href="{{ path('app_collaborateur_edit', {'id': collaborateur.id}) }}">
										<button class="btn btn-success">Modifier</button>
										{# prevoir un bouton pour voir cette facture!! #}
									</a>
									{# <a href="{{ path('app_mail') }}"> #}
										<button class="btn btn-success">MAIL</button>
										{# prevoir un bouton pour voir cette facture!! #}
									</a>
								</div>
							</div>
						{% else %}
							<tr>
								<td colspan="6">Aucun client/collaborateur enregistrer pour le moment !</td>
							</tr>
						{% endfor %}
					</div>
					{{ knp_pagination_render(pagination) }}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {#{{ include('user/_form.html.twig') }}#}
        {# <h1>Formulaires</h1>
             <form>
                <div class="row mb-3">
                    <div class="col">
                      <input type="text" class="form-control" placeholder="Nom">
                    </div>
                    <div class="col">
                      <input type="text" class="form-control" placeholder="Prénom">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                      <input type="text" class="form-control" placeholder="Nom">
                    </div>
                    <div class="col">
                      <input type="text" class="form-control" placeholder="Prénom">
                    </div>
                </div>
            </form> #}
    


    {{ form_start(form, {'attr': {'id': 'new_edit_utilisateur'}}) }}
    {# utilisation de classes bootstrap pour la mise en forme #}
        <div class="row">
                <div class="col-12">
                        {{ form_label(form.email) }}
                        {{ form_widget(form.email) }}
                </div>
                <div class="col-12">
                        {{ form_label(form.password) }}
                        {{ form_widget(form.password) }}
                </div>
                <div class="col-12">
                        <label for="verifpass">Saisir une seconde fois le mot de passe</label>
                        <input type="password" id="verifpass" required>
                </div>
        </div>
        <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

<a href="{{ path('app_user_profil') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user_profil') }}">back to list</a>

    <a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}